const header=document.querySelector('header');
addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>30),{passive:true});
const menuButton=document.querySelector('.menu-toggle'),menu=document.querySelector('#mobile-menu');
function closeMenu(){menu.hidden=true;menuButton.setAttribute('aria-expanded','false');document.body.classList.remove('modal-open');}
menuButton.addEventListener('click',event=>{const open=menuButton.getAttribute('aria-expanded')==='true';menu.hidden=open;menuButton.setAttribute('aria-expanded',String(!open));document.body.classList.toggle('modal-open',!open);if(!open&&event.detail===0)menu.querySelector('a').focus({preventScroll:true});});
menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{closeMenu();const target=document.querySelector(a.getAttribute('href'));target.setAttribute('tabindex','-1');target.focus({preventScroll:true});}));
document.addEventListener('keydown',e=>{if(menu.hidden)return;if(e.key==='Escape'){closeMenu();menuButton.focus();}if(e.key==='Tab'){const links=[menuButton,...menu.querySelectorAll('a')];const first=links[0],last=links.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
matchMedia('(min-width:801px)').addEventListener('change',e=>{if(e.matches)closeMenu();});
if('IntersectionObserver'in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('js-motion');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.07});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}
const articles=[
{category:'CONTRATOS',date:'18 de setembro de 2026 · Data demonstrativa',title:'Contratos em momentos de expansão: o que merece atenção?',body:'<p>Uma empresa em expansão passa a conviver com novas relações, prazos e compromissos. O contrato acompanha esse movimento: ele registra expectativas e organiza como cada parte participa da operação.</p><h3>O negócio vem antes da minuta</h3><p>Antes de discutir redação, vale compreender a relação que está sendo construída. Qual é o objetivo comercial? Quais entregas dependem de terceiros? Que mudanças de escala já estão no horizonte? Essas perguntas ajudam a contextualizar a conversa jurídica.</p><h3>Clareza durante toda a relação</h3><p>Responsabilidades, critérios de acompanhamento e formas de diálogo merecem atenção tanto quanto o início da parceria. Em uma operação em crescimento, o documento precisa ser compreensível também para quem vai utilizá-lo no cotidiano.</p><h3>Uma leitura conectada</h3><p>Reunir as perspectivas jurídica, financeira e operacional permite enxergar o contrato como parte do negócio. A expansão fica mais bem compreendida quando seus compromissos são analisados em conjunto, e não isoladamente.</p>'},
{category:'GOVERNANÇA',date:'10 de setembro de 2026 · Data demonstrativa',title:'Governança como ferramenta para empresas em crescimento',body:'<p>À medida que uma empresa cresce, as decisões passam a envolver mais pessoas e interesses. O que antes era resolvido em uma conversa pode exigir uma estrutura mais clara de responsabilidades e acompanhamento.</p><h3>Quem participa de cada decisão?</h3><p>Governança começa com uma reflexão sobre papéis. É uma conversa sobre quem propõe, quem analisa, quem decide e como as informações circulam. A estrutura precisa dialogar com o momento e a cultura da empresa.</p><h3>Organização com propósito</h3><p>Reuniões, registros e rotinas só fazem sentido quando apoiam o trabalho. Uma estrutura compreensível pode ajudar a preservar a memória das decisões e tornar mais visíveis os compromissos assumidos.</p><h3>Crescer também é revisar</h3><p>Novos sócios, novas atividades e novas prioridades podem mudar a maneira como a empresa funciona. Rever periodicamente os espaços de decisão é parte da reflexão sobre continuidade e desenvolvimento do negócio.</p>'},
{category:'SOCIETÁRIO',date:'2 de setembro de 2026 · Data demonstrativa',title:'Decisões societárias: quando estrutura e estratégia precisam conversar',body:'<p>Uma decisão societária raramente se limita a um documento. Ela reflete como as pessoas pretendem trabalhar juntas, compartilhar responsabilidades e construir os próximos passos da empresa.</p><h3>Estrutura a serviço de uma direção</h3><p>O desenho das relações entre sócios começa pela compreensão dos objetivos. Expansão, entrada de um investidor ou reorganização interna trazem perguntas distintas sobre participação, gestão e continuidade.</p><h3>Expectativas precisam de espaço</h3><p>Conversar sobre horizontes de tempo, participação no cotidiano e prioridades permite identificar pontos que precisam de maior clareza. A dimensão humana dessas escolhas faz parte da análise, ao lado da dimensão técnica.</p><h3>Uma perspectiva de conjunto</h3><p>Estrutura e estratégia se aproximam quando a conversa considera o momento atual e os cenários futuros do negócio. O trabalho jurídico participa dessa construção ao organizar questões e tornar as alternativas mais compreensíveis.</p>'}
];
const articleDialog=document.querySelector('#article-dialog');let previousFocus;
function openDialog(dialog){previousFocus=document.activeElement;dialog.showModal();document.body.classList.add('modal-open');dialog.scrollTop=0;}
function closeDialog(dialog){dialog.close();}
document.querySelectorAll('[data-article]').forEach(button=>button.addEventListener('click',()=>{const a=articles[Number(button.dataset.article)];document.querySelector('#article-category').textContent=a.category;document.querySelector('#article-title').textContent=a.title;document.querySelector('#article-date').textContent=a.date;document.querySelector('#article-body').innerHTML=a.body;openDialog(articleDialog);}));
document.querySelector('#contact-button').addEventListener('click',()=>openDialog(document.querySelector('#contact-dialog')));
document.querySelectorAll('dialog').forEach(dialog=>{dialog.querySelectorAll('.dialog-close,.close-contact').forEach(button=>button.addEventListener('click',()=>closeDialog(dialog)));dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');previousFocus?.focus({preventScroll:true});});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(dialog);}});});
